# Google Maven
# https://maven.google.com/web/index.html?hl=zh-cn

# Gradle Plugins
# https://plugins.gradle.org/

# Maven
# https://mvnrepository.com/

[versions]
agp = "8.13.2"

[plugins]
agp-lib = { id = "com.android.library", version.ref = "agp" }
agp-app = { id = "com.android.application", version.ref = "agp" }

[libraries]
annotation = { group = "androidx.annotation", name = "annotation", version = "1.9.1" }
commons-cli = { group = "commons-cli", name = "commons-cli", version = "1.11.0" }
hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version = "6.1" }
